Repository Catch-y/iOS_Front, pull requests merged in 2025-01, with the labels that each got.

#6 Feat/onboarding
  Catchy/Catchy/API/Auth/AppleLoginManager.swift
  Catchy/Catchy/API/Auth/KakaoLoginManager.swift
  Catchy/Catchy/Common/Protocol/ImageHandling.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomNavigation.swift
  Catchy/Catchy/Common/UIComponents/Custom/MainBtn.swift
  Catchy/Catchy/Common/UIComponents/TestFile.swift
  Catchy/Catchy/Model/Response/ApplUserData.swift
  Catchy/Catchy/Modules/Login/Views/LoginView.swift
  Catchy/Catchy/Modules/Onboarding/Views/OnboardingView.swift
  Catchy/Catchy/Modules/SignUp/ViewModels/SignUpViewModel.swift
  Catchy/Catchy/Modules/SignUp/Views/SignUpView.swift
  Catchy/Catchy/Resources/Assets.xcassets/ETC/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/ETC/close.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/ETC/close.imageset/close.pdf
  Catchy/Catchy/Resources/Assets.xcassets/ETC/leftChevron.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/ETC/leftChevron.imageset/leftChevron.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Login/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Login/appIcon.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Login/appIcon.imageset/appIcon.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Login/apple.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Login/apple.imageset/apple.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Login/kakao.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Login/kakao.imageset/kakao.pdf
  Catchy/Catchy/Resources/Assets.xcassets/SignUp/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/SignUp/signupProfile.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/SignUp/signupProfile.imageset/signupProfile.pdf
  Catchy/Catchy/Resources/Assets.xcassets/onboarding/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/onboarding/logo.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/onboarding/logo.imageset/logo.pdf
  Catchy/Catchy/Resources/Fonts/Font.swift
  Catchy/Catchy/Resources/Image/Icon.swift
  Catchy/Catchy/Resources/ImagePicker/ImagePicker.swift
Labels: :lipstick: UI, :sparkles: Feature

#12 Feat/home view
  Catchy/Catchy/Common/Enum/CategoryType.swift
  Catchy/Catchy/Common/Enum/CourseType.swift
  Catchy/Catchy/Common/Enum/SubCategory.swift
  Catchy/Catchy/Common/Enum/searchTextField.swift
  Catchy/Catchy/Common/Protocol/SubCategoryProtocol.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomLogoNavi.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomTextField.swift
  Catchy/Catchy/Common/UIComponents/Home/CourseCard.swift
  Catchy/Catchy/Common/UIComponents/Home/PopularCourseCard.swift
  Catchy/Catchy/Common/UIComponents/Home/RecommendPlaceCard.swift
  Catchy/Catchy/Common/UIComponents/LikeButton.swift
  Catchy/Catchy/Model/Response/Home/CourseInfoResponse.swift
  Catchy/Catchy/Model/Response/Home/PopularCourseResponse.swift
  Catchy/Catchy/Model/Response/Home/RecommendPlaceResponse.swift
  Catchy/Catchy/Modules/Home/Views/HomeView.swift
  Catchy/Catchy/Resources/Assets.xcassets/ETC/search.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/ETC/search.imageset/Group 298.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Home/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Home/empyHeart.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Home/empyHeart.imageset/empyHeart.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Home/heart.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Home/heart.imageset/heart.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Home/location.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Home/location.imageset/location.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Home/star.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Home/star.imageset/star.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Home/time.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Home/time.imageset/time.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Home/topLogo.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Home/topLogo.imageset/topLogo.png
  Catchy/Catchy/Resources/DataFormatter/DataFormatter.swift
  Catchy/Catchy/Resources/Fonts/Font.swift
  Catchy/Catchy/Resources/Image/Icon.swift
  Catchy/Catchy/Resources/Shadow/ShadowReuse.swift
Labels: :lipstick: UI

#9 그룹탭 - 캘린더
  Catchy/Catchy/Common/UIComponents/Calender/CalenderModel.swift
  Catchy/Catchy/Common/UIComponents/Calender/CalenderView.swift
  Catchy/Catchy/Common/UIComponents/Calender/CalenderViewModel.swift
Labels: :lipstick: UI

#23 UIKit 코드 삭제
  Catchy/Catchy/API/Auth/AppleLoginManager.swift
  Catchy/Catchy/Resources/Assets.xcassets/Course/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/add.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/add.imageset/add.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Course/add_clicked.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/add_clicked.imageset/add_clicked.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Course/courseAI.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/courseAI.imageset/courseAI.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Course/courseDIY.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/courseDIY.imageset/courseDIY.pdf
  Catchy/Catchy/Resources/Extension/UIImage.swift
  Catchy/Catchy/Resources/Image/Icon.swift
  Catchy/Catchy/Resources/Shadow/UIKitShadowReuse.swift
Labels: :star: Important

#26 ✨ 제네릭 세그먼트 컴포넌트 생성
  Catchy/Catchy/API/Protocol/SegmentProtocol.swift
  Catchy/Catchy/Common/Enum/CourseSegment.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomSegment.swift
  Catchy/Catchy/Common/UIComponents/Custom/TestSeg.swift
  Catchy/Catchy/Resources/Assets.xcassets/Course/add.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/add.imageset/add.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Course/add_clicked.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/add_clicked.imageset/add_clicked.pdf
  Catchy/Catchy/Resources/Assets.xcassets/ETC/close.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/ETC/close.imageset/close.pdf
Labels: :lipstick: UI

#30 Feat/flow signup user
  Catchy/Catchy/API/APITarget/AuthAPITarget.swift
  Catchy/Catchy/API/Protocol/Auth/AuthRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/Auth/AuthServiceProtocol.swift
  Catchy/Catchy/API/Protocol/Auth/AuthUseCaseProtocol.swift
  Catchy/Catchy/API/Repository/AuthRepository.swift
  Catchy/Catchy/API/Repository/TestRepo.swift
  Catchy/Catchy/API/Service/AuthService.swift
  Catchy/Catchy/API/Service/TestService.swift
  Catchy/Catchy/API/UseCase/AuthUseCase.swift
  Catchy/Catchy/API/UseCase/TestUsecase.swift
  Catchy/Catchy/APP/AppFlowViewModel.swift
  Catchy/Catchy/APP/CatchyApp.swift
  Catchy/Catchy/Common/Enum/APIError.swift
  Catchy/Catchy/Common/Enum/AppState.swift
  Catchy/Catchy/Common/Enum/SearchTextField.swift
  Catchy/Catchy/Common/Enum/SocialLoginType.swift
  Catchy/Catchy/Common/Protocol/SegmentProtocol.swift
  Catchy/Catchy/Core/DIContainer/UseCaseProvider.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationDestination.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationRoutingView.swift
  Catchy/Catchy/Info.plist
  Catchy/Catchy/Model/Request/SignupRequest.swift
  Catchy/Catchy/Model/Request/TestDTO.swift
  Catchy/Catchy/Model/Response/Auth/SocialLoginResponse.swift
  Catchy/Catchy/Model/Social/AppleUserInfo.swift
  Catchy/Catchy/Model/Social/KakaoUserInfo.swift
  Catchy/Catchy/Model/Social/SignUpNaviData.swift
  Catchy/Catchy/Modules/Login/ViewModel/LoginViewModel.swift
  Catchy/Catchy/Modules/Login/Views/LoginView.swift
  Catchy/Catchy/Modules/Onboarding/Views/OnboardingView.swift
  Catchy/Catchy/Modules/SignUp/ViewModels/SignUpViewModel.swift
  Catchy/Catchy/Modules/SignUp/Views/SignUpView.swift
  Catchy/Catchy/Resources/Fonts/Font.swift
Labels: :lipstick: UI, :sparkles: Feature

#33 코스 뷰 구현
  Catchy/Catchy.xcodeproj/project.pbxproj
  Catchy/Catchy/Common/Enum/CategoryType.swift
  Catchy/Catchy/Common/Enum/CourseSegment.swift
  Catchy/Catchy/Common/UIComponents/Course/AddFloatingButton.swift
  Catchy/Catchy/Common/UIComponents/Course/CategoryCard.swift
  Catchy/Catchy/Common/UIComponents/Course/CourseGroupCard.swift
  Catchy/Catchy/Common/UIComponents/Course/DropDown.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomLogoNavi.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomSegment.swift
  Catchy/Catchy/Common/UIComponents/Home/HomeCourseCard.swift
  Catchy/Catchy/Model/Response/Course/AddressResponse.swift
  Catchy/Catchy/Model/Response/Course/CourseResponse.swift
  Catchy/Catchy/Modules/Course/ViewModels/CourseViewModel.swift
  Catchy/Catchy/Modules/Course/Views/CourseView.swift
  Catchy/Catchy/Resources/Assets.xcassets/Course/check.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/check.imageset/check.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Course/downChevron.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/downChevron.imageset/downChevron.pdf
  Catchy/Catchy/Resources/Extension/StringExtension.swift
  Catchy/Catchy/Resources/Image/Icon.swift
  Catchy/Catchy/Resources/Shadow/UIKitShadowReuse.swift
Labels: :lipstick: UI, :sparkles: Feature

#39 코스 뷰 API 구현 및 레이아웃 수정
  Catchy/Catchy/API/APITarget/CourseManagementAPITarget.swift
  Catchy/Catchy/API/Protocol/CourseManagement/CourseManagementRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/CourseManagement/CourseManagementServiceProtocol.swift
  Catchy/Catchy/API/Protocol/CourseManagement/CourseManagementUseCaseProtocol.swift
  Catchy/Catchy/API/Repository/CourseManamentRepository.swift
  Catchy/Catchy/API/Service/CourseManagementService.swift
  Catchy/Catchy/API/UseCase/CourseManagementUseCase.swift
  Catchy/Catchy/APP/CatchyApp.swift
  Catchy/Catchy/Common/UIComponents/Course/CourseGroupCard.swift
  Catchy/Catchy/Common/UIComponents/Course/DropDown.swift
  Catchy/Catchy/Core/DIContainer/UseCaseProvider.swift
  Catchy/Catchy/Core/Util/Secret.xcconfig
  Catchy/Catchy/Model/Request/Course/CourseRequest.swift
  Catchy/Catchy/Model/Response/Course/CourseResponse.swift
  Catchy/Catchy/Modules/Course/ViewModels/CourseViewModel.swift
  Catchy/Catchy/Modules/Course/Views/CourseView.swift
Labels: :globe_with_meridians: API, :hammer: Refactor, :lipstick: UI, :sparkles: Feature

#41 코스 뷰 UI 수정 및 리팩토링
  Catchy/Catchy.xcodeproj/project.pbxproj
  Catchy/Catchy/Common/UIComponents/Course/CategoryCard.swift
  Catchy/Catchy/Common/UIComponents/Course/CourseGroupCard.swift
  Catchy/Catchy/Common/UIComponents/Course/DropDown.swift
  Catchy/Catchy/Modules/Course/Views/CourseView.swift
  Catchy/Catchy/Resources/Fonts/Font.swift
Labels: :hammer: Refactor, :lipstick: UI

#47 장소 상세 화면 구현
  Catchy/Catchy/API/APITarget/CourseManagementAPITarget.swift
  Catchy/Catchy/API/Protocol/CourseManagement/CourseManagementRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/CourseManagement/CourseManagementServiceProtocol.swift
  Catchy/Catchy/API/Protocol/CourseManagement/CourseManagementUseCaseProtocol.swift
  Catchy/Catchy/API/Repository/CourseManamentRepository.swift
  Catchy/Catchy/API/Service/CourseManagementService.swift
  Catchy/Catchy/API/UseCase/CourseManagementUseCase.swift
  Catchy/Catchy/Common/Enum/CategoryType.swift
  Catchy/Catchy/Common/Enum/CourseSegment.swift
  Catchy/Catchy/Common/UIComponents/Course/CourseGroupCard.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceAddressText.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceCard.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceDomainButton.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceInfoSection.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceRatingText.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceReviewButton.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceTimeText.swift
  Catchy/Catchy/Common/UIComponents/Custom/MainBtn.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationDestination.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationRoutingView.swift
  Catchy/Catchy/Model/Request/Course/PlaceDetailRequest.swift
  Catchy/Catchy/Model/Request/Course/PlaceSearchRequest.swift
  Catchy/Catchy/Model/Response/Course/CourseResponse.swift
  Catchy/Catchy/Model/Response/Course/PlaceDetailResponse.swift
  Catchy/Catchy/Model/Response/Course/PlaceSearchResponse.swift
  Catchy/Catchy/Model/Social/SignUpNaviData.swift
  Catchy/Catchy/Modules/Course/ViewModels/CourseViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/PlaceSearchViewModel.swift
  Catchy/Catchy/Modules/Course/Views/CourseView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceDetailView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceSearchView.swift
  Catchy/Catchy/Resources/Assets.xcassets/Course/domain.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/domain.imageset/Union.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Course/smileSearch.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/smileSearch.imageset/Group 735.pdf
  Catchy/Catchy/Resources/Image/Icon.swift
Labels: :globe_with_meridians: API, :lipstick: UI, :sparkles: Feature

#50 Feat/preferrence survey
  Catchy/Catchy/APP/CatchyApp.swift
  Catchy/Catchy/Common/Enum/CompanionType.swift
  Catchy/Catchy/Common/UIComponents/Course/CourseGroupCard.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomTimePicker.swift
  Catchy/Catchy/Common/UIComponents/Preference/CompanionSelectionBtn.swift
  Catchy/Catchy/Common/UIComponents/Preference/DateSelectButton.swift
  Catchy/Catchy/Common/UIComponents/Preference/SubCategoryBtn.swift
  Catchy/Catchy/Modules/Course/Views/CourseView.swift
  Catchy/Catchy/Modules/Preference/ViewModel/PreferenceViewModel.swift
  Catchy/Catchy/Modules/Preference/Views/PreferencePageView.swift
  Catchy/Catchy/Resources/Assets.xcassets/Preference/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Preference/allCheckBtn.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Preference/allCheckBtn.imageset/allCheckBtn.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Preference/allSelectCheckBtn.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Preference/allSelectCheckBtn.imageset/allSelectCheckBtn.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Preference/korea_map.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Preference/korea_map.imageset/korea_map.pdf
  Catchy/Catchy/Resources/Image/Icon.swift
  Catchy/Catchy/Resources/Json/Sido.geojson
Labels: :globe_with_meridians: API, :hammer: Refactor, :lipstick: UI
