Repository Catch-y/iOS_Front, pull requests merged in 2025-02, with the labels that each got.

#56 Feay/preference map
  Catchy/Catchy/API/APITarget/ProvinceAPITarget.swift
  Catchy/Catchy/API/APITarget/Test.swift
  Catchy/Catchy/API/Util/ProvinceManager/GetProvinceViewModel.swift
  Catchy/Catchy/API/Util/ProvinceManager/ProvinceAccessTokenResponse.swift
  Catchy/Catchy/API/Util/ProvinceManager/ProvinceService.swift
  Catchy/Catchy/API/Util/ProvinceManager/ProvinceTestView.swift
  Catchy/Catchy/API/Util/ProvinceManager/ProvinceTokenManager.swift
  Catchy/Catchy/Common/Enum/ProvinceType.swift
  Catchy/Catchy/Common/UIComponents/Preference/SelectDistrictBtn.swift
  Catchy/Catchy/Model/Response/Province/DistrictResponse.swift
  Catchy/Catchy/Model/Response/Province/ProvinceResponse.swift
  Catchy/Catchy/Modules/Preference/ViewModel/PreferenceViewModel.swift
  Catchy/Catchy/Modules/Preference/Views/PolygonShape.swift
  Catchy/Catchy/Modules/Preference/Views/PreferencePageView.swift
  Catchy/Catchy/Resources/Color.xcassets/Map/Chungcheongbuk.colorset/Contents.json
  Catchy/Catchy/Resources/Color.xcassets/Map/Chungcheongnam.colorset/Contents.json
  Catchy/Catchy/Resources/Color.xcassets/Map/Contents.json
  Catchy/Catchy/Resources/Color.xcassets/Map/Daegu.colorset/Contents.json
  Catchy/Catchy/Resources/Color.xcassets/Map/Gangwon.colorset/Contents.json
  Catchy/Catchy/Resources/Color.xcassets/Map/Gwangju.colorset/Contents.json
  Catchy/Catchy/Resources/Color.xcassets/Map/Gyeonggi.colorset/Contents.json
  Catchy/Catchy/Resources/Color.xcassets/Map/Gyeongsangnam.colorset/Contents.json
  Catchy/Catchy/Resources/Color.xcassets/Map/Incheon.colorset/Contents.json
  Catchy/Catchy/Resources/Color.xcassets/Map/Jellanam.colorset/Contents.json
  Catchy/Catchy/Resources/Color.xcassets/Map/Sejong.colorset/Contents.json
  Catchy/Catchy/Resources/Color.xcassets/Map/busan.colorset/Contents.json
  Catchy/Catchy/Resources/Color.xcassets/Map/daejeon.colorset/Contents.json
  Catchy/Catchy/Resources/Color.xcassets/Map/gyeongsangbuk.colorset/Contents.json
  Catchy/Catchy/Resources/Color.xcassets/Map/jeju.colorset/Contents.json
  Catchy/Catchy/Resources/Color.xcassets/Map/jeollabuk.colorset/Contents.json
  Catchy/Catchy/Resources/Color.xcassets/Map/seoul.colorset/Contents.json
  Catchy/Catchy/Resources/Color.xcassets/Map/ulsan.colorset/Contents.json
  Catchy/Catchy/Resources/Json/Sido.geojson
Labels: :globe_with_meridians: API, :hammer: Refactor, :sparkles: Feature

#52 평점 / 리뷰 및 신고하기 뷰 구현
  Catchy/Catchy/API/APITarget/PlaceAPITarget.swift
  Catchy/Catchy/API/APITarget/ReviewAPITarget.swift
  Catchy/Catchy/API/APITarget/ReviewReportAPITarget.swift
  Catchy/Catchy/API/Protocol/Place/PlaceRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/Place/PlaceServiceProtocol.swift
  Catchy/Catchy/API/Protocol/Place/PlaceUseCaseProtocol.swift
  Catchy/Catchy/API/Protocol/Review/ReviewRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/Review/ReviewServiceProtocol.swift
  Catchy/Catchy/API/Protocol/Review/ReviewUseCaseProtocol.swift
  Catchy/Catchy/API/Protocol/ReviewReport/ReviewReportRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/ReviewReport/ReviewReportServiceProtocol.swift
  Catchy/Catchy/API/Protocol/ReviewReport/ReviewReportUseCaseProtocol.swift
  Catchy/Catchy/API/Repository/PlaceRepository.swift
  Catchy/Catchy/API/Repository/ReviewReportRepository.swift
  Catchy/Catchy/API/Repository/ReviewRepository.swift
  Catchy/Catchy/API/Service/PlaceService.swift
  Catchy/Catchy/API/Service/ReviewReportService.swift
  Catchy/Catchy/API/Service/ReviewService.swift
  Catchy/Catchy/API/UseCase/PlaceUseCase.swift
  Catchy/Catchy/API/UseCase/ReviewReportUseCase.swift
  Catchy/Catchy/API/UseCase/ReviewUseCase.swift
  Catchy/Catchy/Common/Enum/ReviewReportReason.swift
  Catchy/Catchy/Common/Enum/ReviewType.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomNavigation.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomTextEditor.swift
  Catchy/Catchy/Common/UIComponents/Review/ReportItem.swift
  Catchy/Catchy/Common/UIComponents/Review/ReviewCard.swift
  Catchy/Catchy/Common/UIComponents/Review/ReviewGraph.swift
  Catchy/Catchy/Common/UIComponents/Review/StarRating.swift
  Catchy/Catchy/Core/DIContainer/UseCaseProvider.swift
  Catchy/Catchy/Model/Request/GetCourse/GetCourseRequest.swift
  Catchy/Catchy/Model/Request/Place/PlaceReviewSubmissionRequest.swift
  Catchy/Catchy/Model/Request/Review/GetReviewRequest.swift
  Catchy/Catchy/Model/Request/Review/PostReviewReportRequest.swift
  Catchy/Catchy/Model/Response/Place/PlaceLikedResponse.swift
  Catchy/Catchy/Model/Response/Place/PlaceReviewSubmissionResponse.swift
  Catchy/Catchy/Model/Response/Review/ReviewReportResponse.swift
  Catchy/Catchy/Model/Response/Review/ReviewResponse.swift
  Catchy/Catchy/Modules/Review/ViewModels/ReviewReportViewModel.swift
  Catchy/Catchy/Modules/Review/ViewModels/ReviewsViewModel.swift
  Catchy/Catchy/Modules/Review/Views/ReviewReportView.swift
  Catchy/Catchy/Modules/Review/Views/ReviewView.swift
  Catchy/Catchy/Resources/Assets.xcassets/Home/emptyStar.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Home/emptyStar.imageset/emptyStar.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Review/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Review/checkBtnSelected.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Review/checkBtnSelected.imageset/checkBtnSelected.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Review/checkBtnUnselected.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Review/checkBtnUnselected.imageset/checkBtnUnselected.pdf
  Catchy/Catchy/Resources/Image/Icon.swift
Labels: :lipstick: UI

#57 🔥 주석 제거
  Catchy/Catchy/API/Util/ProvinceManager/ProvinceTokenManager.swift
Labels: :hammer: Refactor

#53 Course 및 PlaceCourse API 작성
  Catchy/Catchy/API/APITarget/CourseAPITarget.swift
  Catchy/Catchy/API/APITarget/CourseManagementAPITarget.swift
  Catchy/Catchy/API/APITarget/PlaceCourseAPITarget.swift
  Catchy/Catchy/API/Protocol/Course/CourseRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/Course/CourseServiceProtocol.swift
  Catchy/Catchy/API/Protocol/Course/CourseUseCaseProtocol.swift
  Catchy/Catchy/API/Protocol/CourseManagement/CourseManagementRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/CourseManagement/CourseManagementServiceProtocol.swift
  Catchy/Catchy/API/Protocol/CourseManagement/CourseManagementUseCaseProtocol.swift
  Catchy/Catchy/API/Protocol/PlaceCourse/PlaceCourseRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/PlaceCourse/PlaceCourseServiceProtocol.swift
  Catchy/Catchy/API/Protocol/PlaceCourse/PlaceCourseUseCaseProtocol.swift
  Catchy/Catchy/API/Repository/CourseManamentRepository.swift
  Catchy/Catchy/API/Repository/CourseRepository.swift
  Catchy/Catchy/API/Repository/PlaceCourseRepository.swift
  Catchy/Catchy/API/Service/CourseManagementService.swift
  Catchy/Catchy/API/Service/CourseService.swift
  Catchy/Catchy/API/Service/PlaceCourseService.swift
  Catchy/Catchy/API/UseCase/CourseManagementUseCase.swift
  Catchy/Catchy/API/UseCase/CourseUseCase.swift
  Catchy/Catchy/API/UseCase/PlaceCourseUseCase.swift
  Catchy/Catchy/Core/DIContainer/UseCaseProvider.swift
  Catchy/Catchy/Model/Request/Course/CourseDIYCreateRequest.swift
  Catchy/Catchy/Model/Request/Course/CourseEditRequest.swift
  Catchy/Catchy/Model/Request/Course/CourseRequest.swift
  Catchy/Catchy/Model/Request/Course/CourseReviewRequest.swift
  Catchy/Catchy/Model/Request/Course/PlaceCategoryRegisterRequest.swift
  Catchy/Catchy/Model/Request/Course/PlaceDetailRequest.swift
  Catchy/Catchy/Model/Request/PlaceCourse/PlaceSearchByCurrentRequest.swift
  Catchy/Catchy/Model/Request/PlaceCourse/PlaceSearchByRegionRequest.swift
  Catchy/Catchy/Model/Response/Course/CourseAICreateResponse.swift
  Catchy/Catchy/Model/Response/Course/CourseBookmarkResponse.swift
  Catchy/Catchy/Model/Response/Course/CourseDIYCreateResponse.swift
  Catchy/Catchy/Model/Response/Course/CourseDeleteResponse.swift
  Catchy/Catchy/Model/Response/Course/CourseDetailResponse.swift
  Catchy/Catchy/Model/Response/Course/CourseEditResponse.swift
  Catchy/Catchy/Model/Response/Course/CourseResponse.swift
  Catchy/Catchy/Model/Response/Course/CourseReviewResponse.swift
  Catchy/Catchy/Model/Response/Course/PlaceCategoryRegisterResponse.swift
  Catchy/Catchy/Model/Response/Course/PlaceVisitResponse.swift
  Catchy/Catchy/Model/Response/PlaceCourse/MyPlaceResponse.swift
  Catchy/Catchy/Model/Response/PlaceCourse/PlaceDetailResponse.swift
  Catchy/Catchy/Model/Response/PlaceCourse/PlaceSearchResponse.swift
  Catchy/Catchy/Modules/Course/ViewModels/CourseViewModel.swift
Labels: :globe_with_meridians: API

#60 🐛 머지 후 컴파일 에러 수정
  Catchy/Catchy/Core/DIContainer/UseCaseProvider.swift
  Catchy/Catchy/Modules/Course/ViewModels/PlaceSearchViewModel.swift
  Catchy/Catchy/Modules/Course/Views/CourseView.swift
Labels: :bug: BugFix

#63 드랍 다운 메뉴 API 연결
  Catchy/Catchy/API/APITarget/CourseAPITarget.swift
  Catchy/Catchy/Common/UIComponents/Course/DropDown.swift
  Catchy/Catchy/Model/Response/Course/CourseDIYCreateResponse.swift
  Catchy/Catchy/Model/Response/Course/CourseDetailResponse.swift
  Catchy/Catchy/Model/Response/PlaceCourse/MyPlaceResponse.swift
  Catchy/Catchy/Model/Response/Province/ProvinceResponse.swift
  Catchy/Catchy/Modules/Course/ViewModels/CourseViewModel.swift
  Catchy/Catchy/Modules/Course/Views/CourseView.swift
Labels: :globe_with_meridians: API

#67 Feat/review
  Catchy/Catchy/API/APITarget/ReviewAPITarget.swift
  Catchy/Catchy/Common/UIComponents/Review/ReviewCard.swift
  Catchy/Catchy/Modules/Review/ViewModels/ReviewReportViewModel.swift
  Catchy/Catchy/Modules/Review/ViewModels/ReviewsViewModel.swift
  Catchy/Catchy/Modules/Review/Views/ReviewReportView.swift
  Catchy/Catchy/Modules/Review/Views/ReviewView.swift
Labels: :hammer: Refactor

#68 카테고리 선택 뷰 구현
  Catchy/Catchy/API/APITarget/PlaceCourseAPITarget.swift
  Catchy/Catchy/APP/CatchyApp.swift
  Catchy/Catchy/Common/UIComponents/Course/CategoryButton.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationDestination.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationRoutingView.swift
  Catchy/Catchy/Model/Response/PlaceCourse/PlaceSearchResponse.swift
  Catchy/Catchy/Modules/Course/ViewModels/PlaceSearchViewModel.swift
  Catchy/Catchy/Modules/Course/Views/CategoryRegisterView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceDetailView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceSearchView.swift
Labels: :lipstick: UI

#73 Feat/search view api
  Catchy/Catchy/API/APITarget/HomeAPITarget.swift
  Catchy/Catchy/API/Protocol/Home/HomeRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/Home/HomeServiceProtocol.swift
  Catchy/Catchy/API/Protocol/Home/HomeUseCaseProtocol.swift
  Catchy/Catchy/API/Repository/HomeRepository.swift
  Catchy/Catchy/API/Service/HomeService.swift
  Catchy/Catchy/API/UseCase/HomeUseCase.swift
  Catchy/Catchy/Common/Enum/CategoryType.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomLogoNavi.swift
  Catchy/Catchy/Common/UIComponents/Home/FlowLayout.swift
  Catchy/Catchy/Common/UIComponents/Home/PopularCourseCard.swift
  Catchy/Catchy/Common/UIComponents/Home/PopularCourseScroll.swift
  Catchy/Catchy/Common/UIComponents/Home/RecommendPlaceCard.swift
  Catchy/Catchy/Common/UIComponents/Home/SearchRecommendPlaceCard.swift
  Catchy/Catchy/Common/UIComponents/LikeButton.swift
  Catchy/Catchy/Core/DIContainer/UseCaseProvider.swift
  Catchy/Catchy/Model/Response/Home/PopularCourseResponse.swift
  Catchy/Catchy/Model/Response/Home/RecommendPlaceResponse.swift
  Catchy/Catchy/Model/Response/Home/SearchPlaceResponse.swift
  Catchy/Catchy/Modules/Home/ViewModels/HomeViewModel.swift
  Catchy/Catchy/Modules/Home/ViewModels/SearchViewModel.swift
  Catchy/Catchy/Modules/Home/Views/HomeView.swift
  Catchy/Catchy/Modules/Home/Views/SearchView/SearchView.swift
  Catchy/Catchy/Resources/Assets.xcassets/Home/emptyResult.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Home/emptyResult.imageset/emptyResult.pdf
  Catchy/Catchy/Resources/Image/Icon.swift
Labels: :lipstick: UI, :sparkles: Feature

#79 장소 평점, 리뷰 남기기 뷰, API 구현
  Catchy/Catchy/API/APITarget/CourseAPITarget.swift
  Catchy/Catchy/API/APITarget/PlaceAPITarget.swift
  Catchy/Catchy/API/Protocol/Place/PlaceRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/Place/PlaceServiceProtocol.swift
  Catchy/Catchy/API/Protocol/Place/PlaceUseCaseProtocol.swift
  Catchy/Catchy/API/Repository/PlaceRepository.swift
  Catchy/Catchy/API/Service/PlaceService.swift
  Catchy/Catchy/API/UseCase/PlaceUseCase.swift
  Catchy/Catchy/Common/Enum/CourseSegment.swift
  Catchy/Catchy/Common/Enum/PlaceReviewInfoText.swift
  Catchy/Catchy/Common/UIComponents/Course/CourseGroupCard.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomTextEditor.swift
  Catchy/Catchy/Common/UIComponents/Review/DateDropDown.swift
  Catchy/Catchy/Common/UIComponents/Review/EmptyReviewPhoto.swift
  Catchy/Catchy/Model/Request/Place/PlaceReviewSubmissionRequest.swift
  Catchy/Catchy/Model/Response/Course/CourseResponse.swift
  Catchy/Catchy/Model/Response/Place/PlaceVisitedDateResponse.swift
  Catchy/Catchy/Modules/Course/ViewModels/CourseViewModel.swift
  Catchy/Catchy/Modules/Course/Views/CourseView.swift
  Catchy/Catchy/Modules/Review/ViewModels/ReviewRegisterViewModel.swift
  Catchy/Catchy/Modules/Review/Views/PlaceReviewRegisterView.swift
Labels: :globe_with_meridians: API, :lipstick: UI, :sparkles: Feature

#76 장소 담기 뷰 구현
  Catchy/Catchy/Common/Enum/CourseSegment.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceBucketCard.swift
  Catchy/Catchy/Common/UIComponents/Protocol/SegmentProtocol.swift
  Catchy/Catchy/Model/Response/Course/CourseResponse.swift
  Catchy/Catchy/Model/Response/PlaceCourse/PlaceDetailResponse.swift
  Catchy/Catchy/Modules/Course/Views/PlaceBucketView.swift
Labels: :lipstick: UI

#80 Feat/home detail api
  Catchy/Catchy/APP/CatchyApp.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomAlert.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomNavigation.swift
  Catchy/Catchy/Modules/Home/ViewModels/CourseDetailViewModel.swift
  Catchy/Catchy/Modules/Home/Views/CourseDetail/CourseDetailView.swift
  Catchy/Catchy/Resources/Assets.xcassets/Course/warningIntro.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/warningIntro.imageset/warningIntro.pdf
  Catchy/Catchy/Resources/DataFormatter/DataFormatter.swift
  Catchy/Catchy/Resources/Image/Icon.swift
Labels: :lipstick: UI, :sparkles: Feature

#71 AI 코스 생성 로딩 뷰 구현
  Catchy/Catchy/Common/UIComponents/Course/AddFloatingButton.swift
  Catchy/Catchy/Modules/Course/ViewModels/AILoadingViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/CourseViewModel.swift
  Catchy/Catchy/Modules/Course/Views/AILoadingView.swift
  Catchy/Catchy/Modules/Course/Views/CourseView.swift
  Catchy/Catchy/Resources/Assets.xcassets/Course/blue_pin.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/blue_pin.imageset/Group 691.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Course/loading.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/loading.imageset/loading.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Course/purple_pin.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/purple_pin.imageset/Group 692.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Course/red_pin.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/red_pin.imageset/Group 689.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Course/yellow_pin.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/yellow_pin.imageset/Group 690.pdf
  Catchy/Catchy/Resources/DataFormatter/DataFormatter.swift
  Catchy/Catchy/Resources/Image/Icon.swift
Labels: :globe_with_meridians: API, :lipstick: UI

#87 App flow check
  Catchy/Catchy.xcodeproj/project.pbxproj
  Catchy/Catchy/API/APITarget/HomeAPITarget.swift
  Catchy/Catchy/API/APITarget/MemeberAPITarget.swift
  Catchy/Catchy/API/APITarget/ReviewAPITarget.swift
  Catchy/Catchy/API/Protocol/Home/HomeRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/Home/HomeServiceProtocol.swift
  Catchy/Catchy/API/Protocol/Home/HomeUseCaseProtocol.swift
  Catchy/Catchy/API/Repository/HomeRepository.swift
  Catchy/Catchy/API/Service/HomeService.swift
  Catchy/Catchy/API/UseCase/HomeUseCase.swift
  Catchy/Catchy/APP/AppDelegate.swift
  Catchy/Catchy/APP/CatchyApp.swift
  Catchy/Catchy/APP/NotificationManager.swift
  Catchy/Catchy/Catchy.entitlements
  Catchy/Catchy/Common/Enum/TabCase.swift
  Catchy/Catchy/Common/UIComponents/Home/RecommendPlaceCard.swift
  Catchy/Catchy/Common/UIComponents/Home/SearchRecommendPlaceCard.swift
  Catchy/Catchy/Common/UIComponents/LikeButton.swift
  Catchy/Catchy/Common/UIComponents/Protocol/Likeable.swift
  Catchy/Catchy/Model/Response/CoreLocation/UserLocation.swift
  Catchy/Catchy/Model/Response/Home/CourseInfoResponse.swift
  Catchy/Catchy/Model/Response/Home/RecommendPlaceResponse.swift
  Catchy/Catchy/Model/Response/Home/SearchPlaceResponse.swift
  Catchy/Catchy/Modules/Home/ViewModels/HomeViewModel.swift
  Catchy/Catchy/Modules/Home/ViewModels/SearchViewModel.swift
  Catchy/Catchy/Modules/Home/ViewModels/SimilarPlacesViewModel.swift
  Catchy/Catchy/Modules/Home/Views/HomeView.swift
  Catchy/Catchy/Modules/Home/Views/SearchView/SearchView.swift
  Catchy/Catchy/Modules/Home/Views/SimilarPlces/SimilarPlaces.swift
  Catchy/Catchy/Modules/Tab/CatchyTabView.swift
  Catchy/Catchy/Modules/Tab/CustomTab.swift
  Catchy/Catchy/Resources/Assets.xcassets/TabIcon/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/TabIcon/course.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/TabIcon/course.imageset/course.pdf
  Catchy/Catchy/Resources/Assets.xcassets/TabIcon/group.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/TabIcon/group.imageset/group.pdf
  Catchy/Catchy/Resources/Assets.xcassets/TabIcon/home.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/TabIcon/home.imageset/home.pdf
  Catchy/Catchy/Resources/Assets.xcassets/TabIcon/mypage.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/TabIcon/mypage.imageset/mypage.pdf
  Catchy/Catchy/Resources/Image/Icon.swift
Labels: :globe_with_meridians: API, :hammer: Refactor, :lipstick: UI, :sparkles: Feature

#88 ♻️ SearchPlaceData liked 수정
  Catchy/Catchy/Model/Response/Home/SearchPlaceResponse.swift
Labels: :globe_with_meridians: API

#90 Feat/home api
  Catchy/Catchy/API/APITarget/HomeAPITarget.swift
  Catchy/Catchy/Common/Enum/TabCase.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomLogoNavi.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomProgressView.swift
  Catchy/Catchy/Common/UIComponents/Home/PopularCourseCard.swift
  Catchy/Catchy/Model/Response/Home/RecommendPlaceResponse.swift
  Catchy/Catchy/Model/Response/Home/SearchPlaceResponse.swift
  Catchy/Catchy/Modules/Home/ViewModels/HomeViewModel.swift
  Catchy/Catchy/Modules/Home/ViewModels/SearchViewModel.swift
  Catchy/Catchy/Modules/Home/Views/HomeView.swift
  Catchy/Catchy/Modules/Home/Views/SearchView/SearchView.swift
  Catchy/Catchy/Modules/Onboarding/Views/OnboardingView.swift
  Catchy/Catchy/Modules/Tab/CatchyTabView.swift
  Catchy/Catchy/Resources/DataFormatter/DataFormatter.swift
  Catchy/Catchy/Resources/Image/Icon.swift
  Catchy/Catchy/Resources/Location/BaseLocationManager.swift
  Catchy/Catchy/Resources/Modifier/TestModifier.swift
Labels: :hammer: Refactor, :lipstick: UI, :sparkles: Feature

#93 [Feat] ✨ HomeView API 연결 및 무한 스크롤링
  Catchy/Catchy/API/APITarget/HomeAPITarget.swift
  Catchy/Catchy/API/Protocol/Home/HomeRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/Home/HomeServiceProtocol.swift
  Catchy/Catchy/API/Protocol/Home/HomeUseCaseProtocol.swift
  Catchy/Catchy/API/Repository/HomeRepository.swift
  Catchy/Catchy/API/Service/HomeService.swift
  Catchy/Catchy/API/UseCase/HomeUseCase.swift
  Catchy/Catchy/API/Util/ProvinceManager/ProvinceTestView.swift
  Catchy/Catchy/APP/CatchyApp.swift
  Catchy/Catchy/Common/UIComponents/Home/HomeCourseCard.swift
  Catchy/Catchy/Common/UIComponents/Home/PopularCourseCard.swift
  Catchy/Catchy/Common/UIComponents/Home/RecommendPlaceCard.swift
  Catchy/Catchy/Modules/Home/ViewModels/SearchViewModel.swift
  Catchy/Catchy/Modules/Home/Views/HomeView.swift
  Catchy/Catchy/Modules/Home/Views/SearchView/SearchView.swift
Labels: :globe_with_meridians: API, :hammer: Refactor, :lipstick: UI

#89 [Feat] 💄 장소 상세화면 UI 구현
  Catchy/Catchy/API/APITarget/CourseAPITarget.swift
  Catchy/Catchy/API/APITarget/PlaceCourseAPITarget.swift
  Catchy/Catchy/API/Service/CourseService.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceInfoSection.swift
  Catchy/Catchy/Model/Response/Course/PlaceVisitResponse.swift
  Catchy/Catchy/Modules/Course/ViewModels/PlaceVisitingViewModel.swift
  Catchy/Catchy/Modules/Course/Views/PlaceDetailView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceVisitingView.swift
  Catchy/Catchy/Resources/Assets.xcassets/Course/colorReview.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/colorReview.imageset/Group 311.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Course/emptyStamp.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/emptyStamp.imageset/Group 787.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Course/visitCheck.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/visitCheck.imageset/Group 328.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Course/visitStamp.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/visitStamp.imageset/Group 767.pdf
  Catchy/Catchy/Resources/Image/Icon.swift
Labels: :lipstick: UI, :sparkles: Feature

#95 [Feat] 페이징 및 리프레시 PR
  Catchy/Catchy/Core/Util/Navigation/NavigationRoutingView.swift
  Catchy/Catchy/Modules/Home/ViewModels/HomeViewModel.swift
  Catchy/Catchy/Modules/Home/ViewModels/SearchViewModel.swift
  Catchy/Catchy/Modules/Home/ViewModels/SimilarPlacesViewModel.swift
  Catchy/Catchy/Modules/Home/Views/HomeView.swift
  Catchy/Catchy/Modules/Home/Views/SearchView/SearchView.swift
  Catchy/Catchy/Modules/Home/Views/SimilarPlces/SimilarPlacesView.swift
Labels: :globe_with_meridians: API, :hammer: Refactor, :lipstick: UI, :sparkles: Feature

#97 [Feat]✨ Home more locatoin View 리프레시 연결 및 방식 수정 PR
  Catchy/Catchy/Modules/Home/ViewModels/SearchViewModel.swift
  Catchy/Catchy/Modules/Home/ViewModels/SimilarPlacesViewModel.swift
  Catchy/Catchy/Modules/Home/Views/SimilarPlces/SimilarPlacesView.swift
Labels: :lipstick: UI, :sparkles: Feature

#98 [Feat] ✨ 장소 상세화면, 방문화면, 코스 상세정보 API 구현 PR
  Catchy/Catchy/API/APITarget/CourseAPITarget.swift
  Catchy/Catchy/API/APITarget/PlaceCourseAPITarget.swift
  Catchy/Catchy/API/Protocol/Course/CourseRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/Course/CourseServiceProtocol.swift
  Catchy/Catchy/API/Protocol/Course/CourseUseCaseProtocol.swift
  Catchy/Catchy/API/Repository/CourseRepository.swift
  Catchy/Catchy/API/Service/CourseService.swift
  Catchy/Catchy/API/UseCase/CourseUseCase.swift
  Catchy/Catchy/Common/UIComponents/Course/AddFloatingButton.swift
  Catchy/Catchy/Common/UIComponents/Course/CourseGroupCard.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceBucketCard.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceCard.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceInfoSection.swift
  Catchy/Catchy/Common/UIComponents/LikeButton.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationDestination.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationRoutingView.swift
  Catchy/Catchy/Model/Request/Course/CourseRequest.swift
  Catchy/Catchy/Model/Response/Course/CourseAICreateResponse.swift
  Catchy/Catchy/Model/Response/Course/CourseDIYCreateResponse.swift
  Catchy/Catchy/Model/Response/Course/CourseDetailResponse.swift
  Catchy/Catchy/Model/Response/Course/CourseEditResponse.swift
  Catchy/Catchy/Model/Response/Course/CourseResponse.swift
  Catchy/Catchy/Model/Response/Course/PlaceVisitResponse.swift
  Catchy/Catchy/Model/Response/PlaceCourse/PlaceDetailResponse.swift
  Catchy/Catchy/Model/Response/PlaceCourse/PlaceSearchResponse.swift
  Catchy/Catchy/Modules/Course/ViewModels/AILoadingViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/AIPlaceListViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/CourseViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/PlaceSearchViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/PlaceVisitingViewModel.swift
  Catchy/Catchy/Modules/Course/Views/AILoadingView.swift
  Catchy/Catchy/Modules/Course/Views/AIPlaceListView.swift
  Catchy/Catchy/Modules/Course/Views/CourseView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceBucketView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceDetailView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceSearchView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceVisitingView.swift
  Catchy/Catchy/Modules/Home/ViewModels/CourseDetailViewModel.swift
  Catchy/Catchy/Modules/Home/Views/CourseDetail/CourseDetailView.swift
  Catchy/Catchy/Modules/Tab/CatchyTabView.swift
Labels: :globe_with_meridians: API, :lipstick: UI, :sparkles: Feature

#100 [Feat] ✨ 장소 방문, 좋아요, 카테고리 등록, 리뷰 API 구현 PR
  Catchy/Catchy/API/APITarget/CourseAPITarget.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceInfoSection.swift
  Catchy/Catchy/Model/Request/Course/PlaceCategoryRegisterRequest.swift
  Catchy/Catchy/Model/Response/PlaceCourse/PlaceDetailResponse.swift
  Catchy/Catchy/Model/Response/PlaceCourse/PlaceSearchResponse.swift
  Catchy/Catchy/Modules/Course/ViewModels/CourseViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/DIYCourseViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/PlaceCategoryRegisterViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/PlaceDetailViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/PlaceVisitingViewModel.swift
  Catchy/Catchy/Modules/Course/Views/CategoryRegisterView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceDetailView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceSearchView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceVisitingView.swift
  Catchy/Catchy/Modules/Home/Views/SimilarPlces/SimilarPlacesView.swift
  Catchy/Catchy/Modules/Review/ViewModels/PlaceReviewRegisterViewModel.swift
  Catchy/Catchy/Modules/Review/Views/PlaceReviewRegisterView.swift
Labels: :globe_with_meridians: API, :hammer: Refactor, :sparkles: Feature

#103 [Docs]💡 주석 추가 및 수정
  Catchy/Catchy/API/APITarget/AuthAPITarget.swift
  Catchy/Catchy/API/APITarget/ProvinceAPITarget.swift
  Catchy/Catchy/API/APITarget/ReviewAPITarget.swift
  Catchy/Catchy/API/APITarget/ReviewReportAPITarget.swift
  Catchy/Catchy/API/Auth/AppleLoginManager.swift
  Catchy/Catchy/API/Auth/KakaoLoginManager.swift
  Catchy/Catchy/API/Protocol/Auth/AuthRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/Auth/AuthServiceProtocol.swift
  Catchy/Catchy/API/Protocol/Auth/AuthUseCaseProtocol.swift
  Catchy/Catchy/API/Protocol/Member/MemberRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/Member/MemberUseCaseProtocol.swift
  Catchy/Catchy/API/Protocol/MyPage/MyPageUseCaseProtocol.swift
  Catchy/Catchy/API/Protocol/Review/ReviewRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/Review/ReviewServiceProtocol.swift
  Catchy/Catchy/API/Protocol/Review/ReviewUseCaseProtocol.swift
  Catchy/Catchy/API/Protocol/ReviewReport/ReviewReportRepositoryProtocol.swift
  Catchy/Catchy/Common/Enum/APIError.swift
  Catchy/Catchy/Common/Enum/ActiveDate.swift
  Catchy/Catchy/Common/Enum/AppState.swift
  Catchy/Catchy/Common/Enum/CategoryType.swift
  Catchy/Catchy/Common/Enum/CompanionType.swift
  Catchy/Catchy/Common/Enum/CourseCardType.swift
  Catchy/Catchy/Common/Enum/CourseSegment.swift
  Catchy/Catchy/Common/Enum/ProvinceType.swift
  Catchy/Catchy/Common/Enum/ReviewReportReason.swift
  Catchy/Catchy/Common/Enum/ReviewSegment.swift
  Catchy/Catchy/Common/Enum/ReviewType.swift
  Catchy/Catchy/Common/Enum/SearchTextField.swift
  Catchy/Catchy/Common/Enum/SocialLoginType.swift
  Catchy/Catchy/Common/Enum/TabCase.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomAlert.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomLogoNavi.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomNavigation.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomPageControl.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomProgressView.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomSegment.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomTextEditor.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomTimePicker.swift
  Catchy/Catchy/Common/UIComponents/Custom/MainBtn.swift
  Catchy/Catchy/Common/UIComponents/Home/FlowLayout.swift
  Catchy/Catchy/Common/UIComponents/Home/HomeCourseCard.swift
  Catchy/Catchy/Common/UIComponents/Home/SearchRecommendPlaceCard.swift
  Catchy/Catchy/Common/UIComponents/MyPage/MypageItem.swift
  Catchy/Catchy/Common/UIComponents/Preference/MainCategoryBtn.swift
  Catchy/Catchy/Common/UIComponents/Preference/SelectDistrictBtn.swift
  Catchy/Catchy/Model/Request/Preference/StepFourStepRquest.swift
  Catchy/Catchy/Modules/Home/ViewModels/CourseDetailViewModel.swift
  Catchy/Catchy/Modules/Home/Views/CourseDetail/CourseDetailView.swift
  Catchy/Catchy/Modules/Home/Views/SearchView/SearchView.swift
  Catchy/Catchy/Modules/Onboarding/Views/OnboardingView.swift
  Catchy/Catchy/Modules/Preference/Views/PolygonShape.swift
  Catchy/Catchy/Modules/Preference/Views/PreferenceDistrictsView.swift
  Catchy/Catchy/Modules/SignUp/ViewModels/SignUpViewModel.swift
  Catchy/Catchy/Modules/Tab/CatchyTabView.swift
  Catchy/Catchy/Resources/DataFormatter/DataFormatter.swift
Labels: :page_facing_up: Docs

#105 [Feat] ✨ 장소 방문 화면, 코스 삭제 API 구현
  Catchy/Catchy/API/APITarget/PlaceCourseAPITarget.swift
  Catchy/Catchy/Common/UIComponents/Course/AddFloatingButton.swift
  Catchy/Catchy/Common/UIComponents/Course/CategoryButton.swift
  Catchy/Catchy/Common/UIComponents/Course/CategoryCard.swift
  Catchy/Catchy/Common/UIComponents/Course/CourseGroupCard.swift
  Catchy/Catchy/Common/UIComponents/Course/DropDown.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceAddressText.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceBucketCard.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceCard.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceDomainButton.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceInfoSection.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceRatingText.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceReviewButton.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceTimeText.swift
  Catchy/Catchy/Common/UIComponents/Custom/CustomTextEditor.swift
  Catchy/Catchy/Common/UIComponents/Protocol/PlaceDataProtocol.swift
  Catchy/Catchy/Model/Response/PlaceCourse/MyPlaceResponse.swift
  Catchy/Catchy/Model/Response/PlaceCourse/PlaceDetailResponse.swift
  Catchy/Catchy/Model/Response/PlaceCourse/PlaceSearchResponse.swift
  Catchy/Catchy/Modules/Course/ViewModels/AIPlaceListViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/CourseViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/DIYCourseViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/PlaceCategoryRegisterViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/PlaceDetailViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/PlaceVisitingViewModel.swift
  Catchy/Catchy/Modules/Course/Views/AILoadingView.swift
  Catchy/Catchy/Modules/Course/Views/AIPlaceListView.swift
  Catchy/Catchy/Modules/Course/Views/CategoryRegisterView.swift
  Catchy/Catchy/Modules/Course/Views/CourseView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceBucketView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceDetailView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceSearchView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceVisitingView.swift
  Catchy/Catchy/Modules/Review/ViewModels/PlaceReviewRegisterViewModel.swift
  Catchy/Catchy/Modules/Review/Views/PlaceReviewRegisterView.swift
  Catchy/Catchy/Modules/Tab/CatchyTabView.swift
Labels: :globe_with_meridians: API, :lipstick: UI, :sparkles: Feature

#107 [Feat] ✨ 홈뷰 네비게이션 Stack 추가 PR
  Catchy/Catchy/Common/UIComponents/Custom/CustomProgressView.swift
  Catchy/Catchy/Common/UIComponents/Home/PopularCourseCard.swift
  Catchy/Catchy/Common/UIComponents/Home/RecommendPlaceCard.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationDestination.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationRoutingView.swift
  Catchy/Catchy/Model/Response/Home/RecommendPlaceResponse.swift
  Catchy/Catchy/Modules/Home/ViewModels/HomeViewModel.swift
  Catchy/Catchy/Modules/Home/ViewModels/SimilarPlacesViewModel.swift
  Catchy/Catchy/Modules/Home/Views/HomeView.swift
  Catchy/Catchy/Modules/Home/Views/SimilarPlces/SimilarPlacesView.swift
Labels: :globe_with_meridians: API, :lipstick: UI, :sparkles: Feature

#108 [Feat] ✨ KFImage 구글 장소 이미지 키 대체 PR
  Catchy/Catchy/API/APITarget/HomeAPITarget.swift
  Catchy/Catchy/Common/UIComponents/Home/RecommendPlaceCard.swift
  Catchy/Catchy/Common/UIComponents/Home/SearchRecommendPlaceCard.swift
  Catchy/Catchy/Modules/Home/Views/SimilarPlces/SimilarPlacesView.swift
  Catchy/Catchy/Resources/DataFormatter/DataFormatter.swift
Labels: :lipstick: UI, :sparkles: Feature

#112 [Feat] ✨ 장소 리뷰 화면 & 코스 삭제 UI 구현 PR
  Catchy/Catchy/Common/UIComponents/Course/PlaceBucketCard.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceCard.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceInfoSection.swift
  Catchy/Catchy/Modules/Course/ViewModels/DIYCourseViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/PlaceDetailViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/PlaceVisitingViewModel.swift
  Catchy/Catchy/Modules/Course/Views/CategoryRegisterView.swift
  Catchy/Catchy/Modules/Course/Views/CourseView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceBucketView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceDetailView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceSearchView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceVisitingView.swift
  Catchy/Catchy/Modules/MyPage/ViewModels/FavoritePlacesVIewModel.swift
  Catchy/Catchy/Modules/MyPage/Views/FavoritePlacesView.swift
  Catchy/Catchy/Modules/Review/Views/PlaceReviewRegisterView.swift
  Catchy/Catchy/Modules/Review/Views/ReviewView.swift
  Catchy/Catchy/Resources/Assets.xcassets/Course/trash.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/trash.imageset/Group 829.pdf
  Catchy/Catchy/Resources/Image/Icon.swift
Labels: :globe_with_meridians: API, :lipstick: UI, :sparkles: Feature

#114 [Fix] 🐛 Course, Place, PlaceCourseAPITarget task 수정 PR
  Catchy/Catchy/API/APITarget/CourseAPITarget.swift
  Catchy/Catchy/API/APITarget/PlaceCourseAPITarget.swift
  Catchy/Catchy/API/Protocol/Course/CourseRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/Course/CourseServiceProtocol.swift
  Catchy/Catchy/API/Protocol/Course/CourseUseCaseProtocol.swift
  Catchy/Catchy/API/Repository/CourseRepository.swift
  Catchy/Catchy/API/Service/CourseService.swift
  Catchy/Catchy/API/UseCase/CourseUseCase.swift
  Catchy/Catchy/Model/Request/Course/CourseDIYCreateRequest.swift
  Catchy/Catchy/Model/Request/Course/CourseEditRequest.swift
  Catchy/Catchy/Model/Request/Course/CourseReviewRequest.swift
  Catchy/Catchy/Model/Request/Course/PlaceCategoryRegisterRequest.swift
  Catchy/Catchy/Modules/Course/ViewModels/PlaceCategoryRegisterViewModel.swift
  Catchy/Catchy/Resources/Assets.xcassets/Course/emptyStamp.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/emptyStamp.imageset/emptyStamp.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Course/red_pin.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/red_pin.imageset/Group 689.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Course/red_pin.imageset/red_pin.pdf
Labels: :globe_with_meridians: API

#118 💄 DIY 코스 생성하기 화면 PR
  Catchy/Catchy/API/APITarget/PlaceCourseAPITarget.swift
  Catchy/Catchy/Modules/Course/ViewModels/AIPlaceListViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/DIYCourseCreateViewModel.swift
  Catchy/Catchy/Modules/Course/Views/CategoryRegisterView.swift
  Catchy/Catchy/Modules/Course/Views/DIYCourseCreateView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceBucketView.swift
  Catchy/Catchy/Resources/Assets.xcassets/Course/addPhoto.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/addPhoto.imageset/addPhoto.pdf
  Catchy/Catchy/Resources/Image/Icon.swift
Labels: :lipstick: UI

#120 [Feat] ✨ 코스 DIY 생성 API 구현 PR
  Catchy/Catchy/API/APITarget/CourseAPITarget.swift
  Catchy/Catchy/API/APITarget/PlaceAPITarget.swift
  Catchy/Catchy/API/Protocol/Course/CourseRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/Course/CourseServiceProtocol.swift
  Catchy/Catchy/API/Protocol/Course/CourseUseCaseProtocol.swift
  Catchy/Catchy/API/Repository/CourseRepository.swift
  Catchy/Catchy/API/Service/CourseService.swift
  Catchy/Catchy/API/UseCase/CourseUseCase.swift
  Catchy/Catchy/Modules/Course/ViewModels/DIYCourseCreateViewModel.swift
  Catchy/Catchy/Modules/Course/Views/DIYCourseCreateView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceBucketView.swift
  Catchy/Catchy/Modules/Review/Views/PlaceReviewRegisterView.swift
Labels: :globe_with_meridians: API, :lipstick: UI, :sparkles: Feature

#123 Refac/mypage
  Catchy/Catchy/API/APITarget/MemeberAPITarget.swift
  Catchy/Catchy/API/Protocol/Member/MemberRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/Member/MemberServiceProtocol.swift
  Catchy/Catchy/API/Protocol/Member/MemberUseCaseProtocol.swift
  Catchy/Catchy/API/Repository/MemberRepository.swift
  Catchy/Catchy/API/Service/MemberService.swift
  Catchy/Catchy/API/UseCase/MemberUseCase.swift
  Catchy/Catchy/APP/AppDelegate.swift
  Catchy/Catchy/APP/CatchyApp.swift
  Catchy/Catchy/Common/Enum/SettingCategory.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationDestination.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationRoutingView.swift
  Catchy/Catchy/Model/Response/MyPage/PatchNicknameResponse.swift
  Catchy/Catchy/Modules/MyPage/ViewModels/NicknameEditViewModel.swift
  Catchy/Catchy/Modules/MyPage/ViewModels/SettingViewModel.swift
  Catchy/Catchy/Modules/MyPage/Views/FavoritePlacesView.swift
  Catchy/Catchy/Modules/MyPage/Views/MyPageView.swift
  Catchy/Catchy/Modules/MyPage/Views/NicknameEditView.swift
  Catchy/Catchy/Modules/MyPage/Views/SettingView.swift
  Catchy/Catchy/Modules/SignUp/ViewModels/SignUpViewModel.swift
  Catchy/Catchy/Modules/Tab/CatchyTabView.swift
Labels: :globe_with_meridians: API, :hammer: Refactor, :lipstick: UI

#124 [Feat] ✨ 코스리뷰 전체보기 뷰 추가
  Catchy/Catchy.xcodeproj/project.pbxproj
  Catchy/Catchy/API/APITarget/HomeAPITarget.swift
  Catchy/Catchy/API/APITarget/MyPageAPITarget.swift
  Catchy/Catchy/API/APITarget/ReviewAPITarget.swift
  Catchy/Catchy/API/APITarget/ReviewReportAPITarget.swift
  Catchy/Catchy/API/Protocol/MyPage/MyPageRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/MyPage/MyPageServiceProtocol.swift
  Catchy/Catchy/API/Protocol/MyPage/MyPageUseCaseProtocol.swift
  Catchy/Catchy/API/Protocol/Review/ReviewRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/Review/ReviewServiceProtocol.swift
  Catchy/Catchy/API/Protocol/Review/ReviewUseCaseProtocol.swift
  Catchy/Catchy/API/Protocol/ReviewReport/ReviewReportRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/ReviewReport/ReviewReportServiceProtocol.swift
  Catchy/Catchy/API/Protocol/ReviewReport/ReviewReportUseCaseProtocol.swift
  Catchy/Catchy/API/Repository/MyPageRepository.swift
  Catchy/Catchy/API/Repository/ReviewReportRepository.swift
  Catchy/Catchy/API/Repository/ReviewRepository.swift
  Catchy/Catchy/API/Service/MyPageService.swift
  Catchy/Catchy/API/Service/ReviewReportService.swift
  Catchy/Catchy/API/Service/ReviewService.swift
  Catchy/Catchy/API/UseCase/MyPageUseCase.swift
  Catchy/Catchy/API/UseCase/ReviewReportUseCase.swift
  Catchy/Catchy/API/UseCase/ReviewUseCase.swift
  Catchy/Catchy/APP/CatchyApp.swift
  Catchy/Catchy/Common/UIComponents/Review/ReviewCard.swift
  Catchy/Catchy/Core/DIContainer/UseCaseProvider.swift
  Catchy/Catchy/Model/Request/Review/ReviewReportRequest.swift
  Catchy/Catchy/Model/Response/MyPage/DeleteReviewResponse.swift
  Catchy/Catchy/Model/Response/MyPage/MyCourseReviewResponse.swift
  Catchy/Catchy/Model/Response/MyPage/MyPlaceReviewResponse.swift
  Catchy/Catchy/Model/Response/Review/CourseReviewInfoResponse.swift
  Catchy/Catchy/Model/Response/Review/ReviewReportResponse.swift
  Catchy/Catchy/Modules/Home/ViewModels/SimilarPlacesViewModel.swift
  Catchy/Catchy/Modules/Home/Views/SimilarPlces/SimilarPlacesView.swift
  Catchy/Catchy/Modules/MyPage/ViewModels/MyPageViewModel.swift
  Catchy/Catchy/Modules/MyPage/ViewModels/MyReviews/MyCourseReviewsViewModel.swift
  Catchy/Catchy/Modules/MyPage/ViewModels/MyReviews/MyPlaceReviewsViewModel.swift
  Catchy/Catchy/Modules/MyPage/Views/MyReviews/MyCourseReviewsView.swift
  Catchy/Catchy/Modules/MyPage/Views/MyReviews/MyPlaceReviewsView.swift
  Catchy/Catchy/Modules/Review/ViewModels/CourseReviewViewModel.swift
  Catchy/Catchy/Modules/Review/ViewModels/PlaceReviewViewModel.swift
  Catchy/Catchy/Modules/Review/ViewModels/ReviewReportViewModel.swift
  Catchy/Catchy/Modules/Review/Views/CourseReviewView.swift
  Catchy/Catchy/Modules/Review/Views/PlaceReviewView.swift
  Catchy/Catchy/Modules/Review/Views/ReviewReportView.swift
Labels: :sparkles: Feature

#129 [Feat] ✨ 장소 리뷰, 담기, 카테고리 화면 간 이동 구현 PR
  Catchy/Catchy/API/APITarget/CourseAPITarget.swift
  Catchy/Catchy/API/APITarget/PlaceAPITarget.swift
  Catchy/Catchy/API/APITarget/PlaceCourseAPITarget.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceBucketCard.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceCard.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceDomainButton.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceInfoSection.swift
  Catchy/Catchy/Common/UIComponents/Protocol/PlaceDataProtocol.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationDestination.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationRoutingView.swift
  Catchy/Catchy/Model/Response/PlaceCourse/MyPlaceResponse.swift
  Catchy/Catchy/Model/Response/PlaceCourse/PlaceDetailResponse.swift
  Catchy/Catchy/Model/Response/PlaceCourse/PlaceSearchResponse.swift
  Catchy/Catchy/Modules/Course/ViewModels/CourseViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/DIYCourseViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/PlaceCategoryRegisterViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/PlaceVisitingViewModel.swift
  Catchy/Catchy/Modules/Course/Views/AIPlaceListView.swift
  Catchy/Catchy/Modules/Course/Views/CategoryRegisterView.swift
  Catchy/Catchy/Modules/Course/Views/CourseView.swift
  Catchy/Catchy/Modules/Course/Views/DIYCourseCreateView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceBucketView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceDetailView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceSearchView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceVisitingView.swift
  Catchy/Catchy/Modules/Review/Views/PlaceReviewRegisterView.swift
Labels: :globe_with_meridians: API, :lipstick: UI, :sparkles: Feature

#133 [Feat] ✨ 애플 맵 기능 추가 및 OSRM
  Catchy/Catchy/API/APITarget/CourseAPITarget.swift
  Catchy/Catchy/API/APITarget/RouteAPITarget.swift
  Catchy/Catchy/API/Protocol/Route/RouteRepositoryProtocol.swift
  Catchy/Catchy/API/Protocol/Route/RouteServiceProtocol.swift
  Catchy/Catchy/API/Protocol/Route/RouteUseCaseProtocol.swift
  Catchy/Catchy/API/Repository/RouteRepository.swift
  Catchy/Catchy/API/Service/RouteService.swift
  Catchy/Catchy/API/UseCase/CourseUseCase.swift
  Catchy/Catchy/API/UseCase/PlaceUseCase.swift
  Catchy/Catchy/API/UseCase/RouteUseCase.swift
  Catchy/Catchy/Common/Enum/CategoryType.swift
  Catchy/Catchy/Core/DIContainer/UseCaseProvider.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationDestination.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationRoutingView.swift
  Catchy/Catchy/Model/Request/Map/OSRMRequest.swift
  Catchy/Catchy/Model/Response/Course/CourseEditResponse.swift
  Catchy/Catchy/Model/Response/Course/PlaceInfoData.swift
  Catchy/Catchy/Model/Response/Map/OSRMResponse.swift
  Catchy/Catchy/Modules/AppleMap/AppleMap.swift
  Catchy/Catchy/Modules/AppleMap/ViewModels/AppleMapViewModel.swift
  Catchy/Catchy/Modules/AppleMap/Views/AppleMapView.swift
  Catchy/Catchy/Modules/AppleMap/Views/FullScreenMap.swift
  Catchy/Catchy/Modules/Home/Views/CourseDetail/CourseDetailView.swift
  Catchy/Catchy/Resources/Assets.xcassets/Map/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Map/clickBarMark.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Map/clickBarMark.imageset/clickBarMark.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Map/clickCafeMark.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Map/clickCafeMark.imageset/clickCafeMark.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Map/clickCultureLifeMark.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Map/clickCultureLifeMark.imageset/clickCultureLifeMark.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Map/clickExperienceMark.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Map/clickExperienceMark.imageset/clickExperienceMark.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Map/clickRestMark.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Map/clickRestMark.imageset/clickRestMark.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Map/clickRestaurantMark.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Map/clickRestaurantMark.imageset/clickRestaurantMark.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Map/clickSportMark.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Map/clickSportMark.imageset/clickSportMark.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Map/notClickBarMark.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Map/notClickBarMark.imageset/notClickBarMark.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Map/notClickCafeMark.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Map/notClickCafeMark.imageset/notClickCafeMark.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Map/notClickCultureLifeMark.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Map/notClickCultureLifeMark.imageset/notClickCultureLifeMark.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Map/notClickExperienceMark.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Map/notClickExperienceMark.imageset/notClickExperienceMark.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Map/notClickRestMark.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Map/notClickRestMark.imageset/notClickRestMark.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Map/notClickRestaurantMark.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Map/notClickRestaurantMark.imageset/notClickRestaurantMark.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Map/notClickSportMark.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Map/notClickSportMark.imageset/notClickSportMark.pdf
  Catchy/Catchy/Resources/Assets.xcassets/Map/zoomMap.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Map/zoomMap.imageset/zoomMap.pdf
  Catchy/Catchy/Resources/Extension/ResizeImage.swift
  Catchy/Catchy/Resources/Image/Icon.swift
Labels: :globe_with_meridians: API, :lipstick: UI

#134 [Feat] ✨ 장소 리뷰 화면, 코스 생성화면 전환 방식 변경
  Catchy/Catchy/Common/Enum/CourseSegment.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceBucketCard.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationDestination.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationRoutingView.swift
  Catchy/Catchy/Model/Response/Course/CourseEditResponse.swift
  Catchy/Catchy/Model/Response/PlaceCourse/PlaceDetailResponse.swift
  Catchy/Catchy/Modules/Course/ViewModels/DIYCourseCreateViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/DIYCourseViewModel.swift
  Catchy/Catchy/Modules/Course/Views/DIYCourseCreateView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceBucketView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceDetailView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceSearchView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceVisitingView.swift
  Catchy/Catchy/Modules/MyPage/ViewModels/FavoritePlacesVIewModel.swift
  Catchy/Catchy/Modules/MyPage/Views/FavoritePlacesView.swift
  Catchy/Catchy/Modules/Review/Views/PlaceReviewView.swift
Labels: :hammer: Refactor

#135 [Feat] ✨ 네비게이션 전환 & DIYBackButton, DITCloseButton, DIYBucketButton 구현 PR
  Catchy/Catchy/API/APITarget/PlaceCourseAPITarget.swift
  Catchy/Catchy/APP/CatchyApp.swift
  Catchy/Catchy/Common/UIComponents/Course/DIYBackButton.swift
  Catchy/Catchy/Common/UIComponents/Course/DIYBucketButton.swift
  Catchy/Catchy/Common/UIComponents/Course/DIYCloseButton.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceBucketCard.swift
  Catchy/Catchy/Common/UIComponents/Course/PlaceInfoSection.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationDestination.swift
  Catchy/Catchy/Core/Util/Navigation/NavigationRoutingView.swift
  Catchy/Catchy/Modules/Course/ViewModels/DIYCourseViewModel.swift
  Catchy/Catchy/Modules/Course/ViewModels/PlaceDetailViewModel.swift
  Catchy/Catchy/Modules/Course/Views/CourseView.swift
  Catchy/Catchy/Modules/Course/Views/DIYCourseCreateView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceBucketView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceDetailView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceSearchView.swift
  Catchy/Catchy/Modules/Tab/CatchyTabView.swift
  Catchy/Catchy/Resources/Assets.xcassets/Course/bucket.imageset/Contents.json
  Catchy/Catchy/Resources/Assets.xcassets/Course/bucket.imageset/bucket.pdf
  Catchy/Catchy/Resources/Image/Icon.swift
Labels: :hammer: Refactor, :lipstick: UI, :sparkles: Feature

#141 [Feat] 마이페이지 뷰들 무한스크롤 구현
  Catchy/Catchy/API/APITarget/PlaceCourseAPITarget.swift
  Catchy/Catchy/API/APITarget/ReviewAPITarget.swift
  Catchy/Catchy/Common/UIComponents/Review/ReviewCard.swift
  Catchy/Catchy/Model/Response/PlaceCourse/MyPlaceResponse.swift
  Catchy/Catchy/Model/Response/Review/PlaceReviewInfoResponse.swift
  Catchy/Catchy/Modules/MyPage/ViewModels/FavoritePlacesVIewModel.swift
  Catchy/Catchy/Modules/MyPage/ViewModels/MyReviews/MyCourseReviewsViewModel.swift
  Catchy/Catchy/Modules/MyPage/ViewModels/MyReviews/MyPlaceReviewsViewModel.swift
  Catchy/Catchy/Modules/MyPage/ViewModels/MyReviews/MyReviewsViewModel.swift
  Catchy/Catchy/Modules/MyPage/Views/FavoritePlacesView.swift
  Catchy/Catchy/Modules/MyPage/Views/MyPageView.swift
  Catchy/Catchy/Modules/MyPage/Views/MyReviews/DeleteReviewPopupView.swift
  Catchy/Catchy/Modules/MyPage/Views/MyReviews/MyCourseReviewsView.swift
  Catchy/Catchy/Modules/MyPage/Views/MyReviews/MyPlaceReviewsView.swift
  Catchy/Catchy/Modules/MyPage/Views/MyReviews/MyReviewsView.swift
  Catchy/Catchy/Modules/MyPage/Views/NicknameEditView.swift
  Catchy/Catchy/Modules/Review/ViewModels/CourseReviewViewModel.swift
  Catchy/Catchy/Modules/Review/ViewModels/PlaceReviewViewModel.swift
  Catchy/Catchy/Modules/Review/Views/CourseReviewView.swift
  Catchy/Catchy/Modules/Review/Views/PlaceReviewView.swift
Labels: :sparkles: Feature

#148 [Feat] ✨ 데이터 추가 PR
  Catchy/Catchy/API/APITarget/HomeAPITarget.swift
Labels: :globe_with_meridians: API

#150 [Recycle] ♻️ 마이페이지뷰, 홈뷰 createProvider / testProvider 구분
  Catchy/Catchy/API/Service/HomeService.swift
  Catchy/Catchy/API/Service/MyPageService.swift
Labels: :hammer: Refactor

#151 [Feat] 💄 무한 스크롤 수정 & testProvider->createProvider PR
  Catchy/Catchy/API/Service/PlaceCourseService.swift
  Catchy/Catchy/API/Service/PlaceService.swift
  Catchy/Catchy/API/Service/ReviewService.swift
  Catchy/Catchy/Modules/Home/ViewModels/SimilarPlacesViewModel.swift
  Catchy/Catchy/Modules/Home/Views/SimilarPlces/SimilarPlacesView.swift
Labels: :globe_with_meridians: API, :lipstick: UI, :sparkles: Feature

#154 [Fix] 🐛 장소 상세, 장소 방문 화면 Progress 최대 넓이 수정 PR
  Catchy/Catchy/API/Service/CourseService.swift
  Catchy/Catchy/Modules/AppleMap/Views/DIYMap.swift
  Catchy/Catchy/Modules/Course/ViewModels/DIYCourseViewModel.swift
  Catchy/Catchy/Modules/Course/Views/AIPlaceListView.swift
  Catchy/Catchy/Modules/Course/Views/CourseView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceDetailView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceSearchView.swift
  Catchy/Catchy/Modules/Course/Views/PlaceVisitingView.swift
  Catchy/Catchy/Modules/MyPage/ViewModels/MyPageViewModel.swift
  Catchy/Catchy/Modules/MyPage/Views/MyPageView.swift
  Catchy/Catchy/Modules/Preference/Views/PreferencePageView.swift
  Catchy/Catchy/Modules/Review/Views/CourseReviewView.swift
  Catchy/Catchy/Modules/Review/Views/PlaceReviewView.swift
Labels: :hammer: Refactor, :lipstick: UI
